version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: iky-server
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3010}
      HOST: ${HOST:-0.0.0.0}
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-iky}
      DB_USER: ${DB_USER:-iky_user}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_POOL_MIN: ${DB_POOL_MIN:-2}
      DB_POOL_MAX: ${DB_POOL_MAX:-10}
      API_PREFIX: ${API_PREFIX:-/api/v1}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      MATCH_CONFIDENCE_THRESHOLD: ${MATCH_CONFIDENCE_THRESHOLD:-0.75}
      DEVICE_CHANGE_THRESHOLD: ${DEVICE_CHANGE_THRESHOLD:-0.5}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
    ports:
      - "${PORT:-3010}:3010"
    volumes:
      - ./server/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3010/api/v1/health', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 3s
      start_period: 10s
      retries: 3

